// Code generated by goctl. DO NOT EDIT.
// Source: check.proto

package checker

import (
	"context"

	"github.com/SeeJson/bookstore/rpc/check/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckReq  = __.CheckReq
	CheckResp = __.CheckResp

	Checker interface {
		Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
	}

	defaultChecker struct {
		cli zrpc.Client
	}
)

func NewChecker(cli zrpc.Client) Checker {
	return &defaultChecker{
		cli: cli,
	}
}

func (m *defaultChecker) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	client := __.NewCheckerClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}
