// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package server

import (
	"context"

	"github.com/SeeJson/bookstore/rpc/add/internal/logic"
	"github.com/SeeJson/bookstore/rpc/add/internal/svc"
	"github.com/SeeJson/bookstore/rpc/add/pb"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *__.AddReq) (*__.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
