// Code generated by goctl. DO NOT EDIT.
// Source: check.proto

package server

import (
	"context"

	"github.com/SeeJson/bookstore/rpc/check/internal/logic"
	"github.com/SeeJson/bookstore/rpc/check/internal/svc"
	"github.com/SeeJson/bookstore/rpc/check/pb"
)

type CheckerServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCheckerServer
}

func NewCheckerServer(svcCtx *svc.ServiceContext) *CheckerServer {
	return &CheckerServer{
		svcCtx: svcCtx,
	}
}

func (s *CheckerServer) Check(ctx context.Context, in *__.CheckReq) (*__.CheckResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
